apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
  namespace: fl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: fl-ksa
      containers:
      - image: 536704830979.dkr.ecr.us-east-1.amazonaws.com/breast-cancer-classifier:latest_eif
        # command: ["bash", "/app/run.sh"]
        command: ["sleep", "36000"]
        imagePullPolicy: Always
        env:
        - name: REGION
          value: us-east-1
        name: server
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/hugepages
          name: hugepage
          readOnly: false
        resources:
          limits:
            aws.ec2.nitro/nitro_enclaves: "1"
            hugepages-1Gi: 21Gi # change according to docker image size (x4)
            cpu: 250m
          requests:
            aws.ec2.nitro/nitro_enclaves: "1"
            hugepages-1Gi: 21Gi # change according to docker image size (x4)
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists