apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
  namespace: fl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: fl-ksa
      containers:
      - image: 536704830979.dkr.ecr.us-east-1.amazonaws.com/simple-ne-client:latest
        # command: ["sleep", "36000"]
        imagePullPolicy: Always
        name: client
        ports:
        # - containerPort: 5000
        - containerPort: 5000
          protocol: TCP
        env:
        - name: CID
          value: "99999"
        - name: ENCRYPTED_DATA_S3_URI
          value: "s3://privacy-computing-assets-us-east-1/encrypted_data.txt"
        - name: KMS_KEY_ID
          value: "arn:aws:kms:us-east-1:536704830979:key/b4c01ff4-8a9f-4ee3-b3fc-87bf852c0369"
        - name: REGION
          value: "us-east-1"