apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
  namespace: fl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: fl-ksa
      containers:
      - image: 536704830979.dkr.ecr.us-east-1.amazonaws.com/simple-ne-client:latest
#        command: ["sleep", "36000"]
        imagePullPolicy: Always
        name: client
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: CID
          value: "16"