apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
  namespace: fl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: fl-ksa
      containers:
        - image: xxxxxx.dkr.ecr.us-east-1.amazonaws.com/breast-cancer-classifier-client-backend:latest
          # command: ["sleep", "36000"] # for testing only
          imagePullPolicy: Always
          name: client
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: CID
              value: "99999"
            - name: REGION
              value: "us-east-1"
            - name: IMAGES_S3_BUCKET_LOCATION
              value: "<NEED INPUT>/source"